### ISSUE TITLE
Team Management APIs 

### ISSUE THREAD

**Issue by ahmadnassri** [probot/settings#101]
The documentation for the team management states:

> NOTE: The APIs needed for teams are not supported yet by GitHub Apps
> https://developer.github.com/v3/apps/available-endpoints/

however the official GitHub API documentation states:

> The following endpoints are available for use by GitHub Apps. Your app can make the following requests using GraphQL v4 or REST v3 endpoints. For more information, see "GitHub Apps."

so perhaps the APIs got updated? and all that's missing to making this work is the preview headers addition?

unless I'm missing something, I'm happy to make a PR to add preview headers.

cheers.

**Comment by simonvanderveldt** [comment]
Can this be reopened? Anyone have any more info on this/if this now works or not?

**Comment by ahmadnassri** [comment]
I belive this is working as expected at this point, and the README is just misleading.

see the code responsible for team management here: https://github.com/probot/settings/blob/master/lib/plugins/teams.js

**Comment by simonvanderveldt** [comment]
@ahmadnassri OK, I guess we'll just have to try then.
Have the GitHub APIs been updated or is this comment at the top of that file still relevant?
> // NOTE: The APIs needed for this plugin are not supported yet by GitHub Apps

**Comment by simonvanderveldt** [comment]
@ahmadnassri OK, I guess we'll just have to try then.
Have the GitHub APIs been updated or is this comment at the top of that file still relevant?

https://github.com/probot/settings/blob/master/lib/plugins/teams.js#L1
