### ISSUE TITLE
Ability to specify list of "oldname" labels to be renamed

### ISSUE THREAD

**Issue by aegershman** [probot/settings#106]
In order to account for consolidating multiple label names into a single label, the `oldname` key should accept a list of labels which will be renamed.

```
  - name: first-timers-only
    # include the old name to rename an existing label
    oldname: ["Help Wanted", "help-wanted", "needs-some-help", "help-me-out-here"]
```

**Comment by aegershman** [comment]
Still relevant

**Comment by aegershman** [comment]
Still relevant. I don't know, I think it's a good idea, I'm just not smart enough to implement it.

**Comment by marcospereira** [comment]
Still relevant.

I can give it a shot if there is some guidance about how to implement it.

**Comment by JoseThen** [comment]
I actually just came upon this use case, would be great to have.

**Comment by JoseThen** [comment]
Still relevant.
