### ISSUE TITLE
Ability to configure whether "projects" or "labels" get deleted if not in settings.yml

### ISSUE THREAD

**Issue by aegershman** [probot/settings#107]
If a project or label is not specified within the `settings.yml`, but they *do* exist on the repository already, then the probot will automatically delete everything which *doesn't* exist within the `settings.yml`. 

I'd like the ability to configure whether things get deleted if they aren't present in the `settings.yml`

**Comment by vidu171** [comment]
I think so we can add a `persist_labels` option inside the `settings.yml` which can make it possible to do so.

**Comment by jeherve** [comment]
Yes, I think it would make a great addition. This way the `settings.yml` file would be a good default set of labels, but would not stop repo owners from adding extra labels without having to edit `settings.yml`.

**Comment by gundalow** [comment]
Is this something that's likely to be done?

I know GitHub has https://github.com/organizations/ORG/settings/labels though I believe they only get applied when a Repo is created.

**Comment by travi** [comment]
it seems like you are asking for something different than the original intent of this issue. 

if you are looking to define a list for all repos in an org, have you considered leveraging the [account-level inheritance](https://github.com/probot/settings#inheritance) that is available? 

if i misunderstood what you are asking for, but it is different preventing deletion, could you open a new issue?

**Comment by gundalow** [comment]
@travi hi, thanks for the quick response. Yes my concern is about labels not defined in `settings.yml` are deleted from my Repos.

The link was incase that might be useful for others as a workaround.
