### ISSUE TITLE
github permissions: why is 'write access' needed

### ISSUE THREAD

**Issue by ahmadnassri** [probot/settings#112]
I'm confused to what reason the app asks for:

- _"**write** access to code"_
- _"**Read** and **write** access to administration, commit statuses, issues, repository projects, and single file"_

> I'm assuming the "single file" in question here is .github/settings.yml`

**write** access shouldn't be needed from the currently exposed functionality?

**Comment by allejo** [comment]
Bumping this as I'd also like to know

**Comment by allejo** [comment]
Still relevant. Any chance @zeke can chime in?

**Comment by hiimbex** [comment]
Code aka "contents" is this permission:

<img width="594" alt="Screen Shot 2019-09-04 at 10 55 37 AM" src="https://user-images.githubusercontent.com/13410355/64278854-98166700-cf02-11e9-9031-36ae58c5b37e.png">

It gives access to these API endpoints to the app: https://developer.github.com/v3/apps/permissions/#permission-on-contents. Branches in particular is require by this app's current functionality.

**Comment by allejo** [comment]
Thanks for the clarification @hiimbex! Should that information be included in [`docs/deploy.md`](https://github.com/probot/settings/blob/master/docs/deploy.md)?

**Comment by larsxschneider** [comment]
@hiimbex Can you help me understand why this app needs those API endpoints?

**Comment by larsxschneider** [comment]
@travi ☝️

**Comment by travi** [comment]
as mentioned above, 

> Branches in particular is require by this app's current functionality.

more specifically, settings [configures branch protection](https://github.com/probot/settings/blob/273ef94d2515bdb7f4e10b5cec7e8b82aababdc1/lib/plugins/branches.js#L17-L22), which is at least one current feature that would not work without access to those API endpoints.

i can admit that i have not been a maintainer long enough to confidently articulate additional reasons for requiring such permission. i certainly would like to require as little access as possible, so i am open to further conversation if optimizations can be made. however, my understanding is that the currently requested permissions are required for full functionality.
