### ISSUE TITLE
Ability to trigger update through commit message

### ISSUE THREAD

**Issue by grrowl** [probot/settings#117]
Since the `settings.yml` might be inherited from a central `.github` repo, it would be nice to not have to modify the `.github/setttings.yml` just to update changes. Ideally it could check the commit messages for a special string such as `[probot-settings update]`, and re-apply the config.

**Comment by kairichard** [comment]
I would totally love that!

**Comment by travi** [comment]
#95 is still open to hopefully address this need at some point, but there is currently no way to apply the changes outside of modifying the settings file
