### ISSUE TITLE
Is the bot working right now?

### ISSUE THREAD

**Issue by joshk0** [probot/settings#130]
We have a bunch of settings.yml files (boilerplate) that have worked for months, now we add them to our repository and the app is still configured on the org, but the changes to not take effect on the repo.

Is there something wrong with the app? We can run our own, but not eager to invest the setup time...

**Comment by mtttcgcg** [comment]
I'm not seeing the hosted bot take any action on my repos either :-(

**Comment by zeke** [comment]
Trying to figure out who owns and runs this service. I'll let you know what I find.

**Comment by jwsloan** [comment]
Unfortunately, if the syntax of the file is not exactly correct, it will fail silently. The changes will not be applied, and you won't know why.

In the case @mtttcgcg is talking about, I think the file is just not in the right location.

In the repository you're using the app in, make sure the path to the file is `.github/settings.yml`. This is regardless of whether you've got a .github repository or not.

**Comment by mtttcgcg** [comment]
Figured out it doesn't appear to work with personal public repos. The same config is working in an org.

**Comment by gr2m** [comment]
ping @travi @jwsloan: does either of you have it working on your personal accounts? Any idea what the problem might be?

**Comment by travi** [comment]
i created [this repo](https://github.com/travi/eslint-config-hal) a couple days ago, with [this config](https://github.com/travi/eslint-config-hal/blob/master/.github/settings.yml), which extends [my account-level config](https://github.com/travi/.github/blob/master/.github/settings.yml). It seems like the settings were applied as I would expect.
