### ISSUE TITLE
Add support for 'auto delete PR head branch'

### ISSUE THREAD

**Issue by Stromweld** [probot/settings#134]
Hi,

  The <a href="https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/" rel="nofollow">auto delete PR head branch</a> feature has been added to GitHub. To define a repository as a template, a checkbox needs to be ticked in the settings. It would be nice to be able to enable it via GitHub Settings.

Thanks.

**Comment by kevo1ution** [comment]
I don't think there is an API request for this yet

**Comment by mvegter** [comment]
Note that this feature is not available on GitHub Enterprise

**Comment by localheinz** [comment]
Interestingly, the API, albeit not documented, supports enabling/disabling the setting via https://developer.github.com/v3/repos/#edit using the `delete_branch_on_merge` key.

However, it looks like it's not supported via `probot/settings`.

**Comment by sjparkinson** [comment]
> Interestingly, the API, albeit not documented, supports enabling/disabling the setting via https://developer.github.com/v3/repos/#edit using the `delete_branch_on_merge` key.

The option is now documented in the API and available in @octokit/rest. Could we get support for this option added to probot/settings now?

I'm also interested to know how you'd go about it, I tried `npm upgrade @octokit/rest` on this project to raise a PR bumping the version in the `package-lock.json`, but that didn't do what I expected.

**Comment by travi** [comment]
> The option is now documented in the API and available in @octokit/rest.
thanks for pointing out that the new key is now documented

> Could we get support for this option added to probot/settings now?
i would expect that simply adding that key to your config under the `repository` section should just work. are you not seeing this as the case?

> I tried npm upgrade @octokit/rest on this project to raise a PR bumping the version in the package-lock.json, but that didn't do what I expected.
`settings` consumes `@octokit/rest` through `probot`, but i would not expect to need an octokit upgrade in order for this to work.

**Comment by sjparkinson** [comment]
Ah neat, thank you for clarifying, I'll give it a spin now!

**Comment by travi** [comment]
sounds good. please do report back and let us know how it went.

**Comment by sstarcher** [comment]
Looks like the golang api for github now supports this - https://github.com/google/go-github/pull/1388

**Comment by travi** [comment]
is it still not working through "settings" if you define it in your `.github/settings.yml`? i have not had a chance to confirm through a live config myself, but i would expect it to get passed through to the api request just like the other properties under the `repository` section

**Comment by sjparkinson** [comment]
> please do report back and let us know how it went.

Unfortunately it doesn't look like it has worked.

We have it defined in https://github.com/Financial-Times/github-apps-config-next/blob/0611ae8d13ac80f1c153d41267fb28436b984fd3/.github/settings.yml#L9, and that hasn't been adopted by any of the repositories that extend that configuration.

A collogue has also tested this option in a self-contained repository to ensure it's not the use of probot-config and extending configuration. Again no luck in getting the option to work as expected.

**Comment by travi** [comment]
ok, thanks for the confirmation. i will try to dig in to understand the detail that i must be missing

**Comment by travi** [comment]
> and that hasn't been adopted by any of the repositories that extend that configuration.

it is worth being aware that it is expected that this change would not apply to extending projects unless you also modified the config for that project. that is something we [hope to improve](https://github.com/probot/settings/issues/95) that, but it isn't currently handled.

**Comment by travi** [comment]
i've at least tested this out on one of my own repos and have confirmed that `delete_branch_on_merge` does not get toggled, but also confirmed that other properties do get toggled while that property is included. that at least tells me that the request is not completely failing.

i need to find time to investigate more deeply to see if the api response reveals more information, but that will take a little bit of work on my side. thank you for the patience as i try to dig deeper.

**Comment by travi** [comment]
i've at least had a chance to confirm that the api does work to toggle this setting using the following request through curl:

```sh
curl -n -H "Content-Type: application/json" -X PATCH -d '{"delete_branch_on_merge": true}' https://api.github.com/repos/travi/any
```

this assertion in my recently added integration test:

https://github.com/probot/settings/blob/136a43fe5c15c2225e50fbb84d1bc08ab990be27/test/integration/push.test.js#L51-L56

in combination with this config used in that test:

https://github.com/probot/settings/blob/136a43fe5c15c2225e50fbb84d1bc08ab990be27/test/fixtures/config.yml#L3

should be confirming that property is being included in the repository edit request.

i don't yet understand that detail that is preventing this from working, but i'm still investigating

**Comment by JasonEtco** [comment]
Hi folks 👋 thank you for all the discussion and investigation here. I've flagged this thread internally, it _could_ be an issue with this field's implementation on the back-end, that prevents it from being set by a GitHub App (vs. a personal access token, which would work). Will update here when I know more 👍

**Comment by travi** [comment]
@JasonEtco any chance you've heard an update on this one?

**Comment by dhoppe** [comment]
@JasonEtco Do you have any news regarding this issue? It would be great to manage this setting via Probot.

**Comment by dhoppe** [comment]
@JasonEtco I do not think that this issue is related to the kind of authentication. I am able to to set ```delete_branch_on_merge: true``` via ```curl``` including the personal access token. 

Probot is doing something, but not what we would expect. It is not able to enable this setting, but if it is already enabled, Probot will disable it. That is even worse. :(

**Comment by AdmiringWorm** [comment]
I just got hit by this when trying to enable automatically deleting head branches.

One thing I found curious, though, was that on a different repo where deleting head branches were already enabled, then when updating the robot configuration file with `delete_branch_on_merge: true` actually turned off the settings.
Which prompted me to test it out a little, and it seems that no matter what value you set `delete_branch_on_merge` to (even tried to set it to a string value), it will turn off the settings if it is already enabled.

**Comment by andreineculau** [comment]
Experiencing the same behaviour as @AdmiringWorm

**Comment by localheinz** [comment]
👍 

Doesn’t work for me.

**Comment by llaski** [comment]
Same case as @AdmiringWorm for me, the `true` value for this field will not turn it the setting on, but if the setting is already enabled and the value in the setting file is `false` it will turn it off.

**Comment by localheinz** [comment]
Thank you, @travi!

**Comment by jsok** [comment]
It's not clear which commit/PR fixed this issue @travi , are you able to link to it?

**Comment by travi** [comment]
the fix was on the github api side, not within the settings app. 

probably not very helpful, but this was the test commit where i confirmed it working: https://github.com/travi-test/settings-test/commit/70e649edea1d5625fb0392edbacc511afd9875a7
