### ISSUE TITLE
Unable to set 'maintain' permission for teams

### ISSUE THREAD

**Issue by fredden** [probot/settings#158]
From what I can tell, `probot/settings` does not support all team permission options. Current [permission levels supported by GitHub](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) are:
* Read
* Triage
* Write
* Maintain
* Admin

However `probot/settings` only seems to support "Read" (aka `pull`), "Write" (aka `push`), & "Admin".

https://github.com/probot/settings/blob/359a2eb7bc48c5b412789df37e6ff1428b9ab7f3/lib/plugins/collaborators.js#L21-L23

![Screenshot_2019-10-30_14-06-04](https://user-images.githubusercontent.com/334786/67864993-74485980-fb1e-11e9-9ff1-389c7f0d13bf.png)

**Comment by travi** [comment]
i noticed this the other day too when i was trying to configure and org level team to have `triage` permission. 

at least in the team case, `settings` simply [passes the config through](https://github.com/probot/settings/blob/359a2eb7bc48c5b412789df37e6ff1428b9ab7f3/lib/plugins/teams.js#L28), but [the api only supports `push`, `pull`, and `admin`](https://developer.github.com/v3/teams/#add-or-update-team-repository).

it appears that the same `settings` behavior exists for [adding the collaborator](https://github.com/probot/settings/blob/359a2eb7bc48c5b412789df37e6ff1428b9ab7f3/lib/plugins/collaborators.js#L43) (the block you highlighted is simply for normalizing the text comparison to determine if updates are necessary from current), but it appears that the api for adding a collaborator [has the same limitation](https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator)

unfortunately, that means that `settings` cannot grant all of the permission levels. if this is important to you, please reach out to github support and request api support. once the api supports this, we should have no trouble handling it through `settings`.

**Comment by fredden** [comment]
Thanks. I've raised this with GitHub support. I wasn't aware it's missing from their API. Very helpful links/information. :+1:

**Comment by fredden** [comment]
This is still pending upstream API changes.

**Comment by travi** [comment]
it appears that the other permission levels are available in the api now, so we should be able to make this work with some minor changes now

**Comment by travi** [comment]
sorry, i was wrong. while it is available for collaborators like i linked to above, it does not yet appear to be available [for teams](https://developer.github.com/v3/teams/#add-or-update-team-repository)

**Comment by travi** [comment]
[the docs show](https://developer.github.com/v3/teams/#add-or-update-team-repository) that this is available now, and i [confirmed that it works](https://github.com/travi-test/settings-test/commit/7a789970daa0368f83d922a246a7a8499ad92e31). i'll update the docs quick, but i think we can close this one out.

**Comment by travi** [comment]
it was brought to my attention in #246 that closing this was premature. we'll need to get octokit upgraded in order to properly support this

**Comment by travi** [comment]
Now that octokit has been upgraded, this should be fixed properly. Integration tests have been added to verify some of the combinations in https://github.com/probot/settings/pull/248
