### ISSUE TITLE
What does the "has_downloads" field do?

### ISSUE THREAD

**Issue by kevo1ution** [probot/settings#159]
I was looking through the octokit/rest documentation, and I could not find a field name for "has_downloads" in their patch request [here](https://developer.github.com/v3/repos/#edit) or in their post request [here](https://developer.github.com/v3/repos/#create). I noticed that the "has_downloads" field is in the response [examples](https://developer.github.com/v3/repos/#response-3) though, and when updating the settings.yml to switch "has_downloads" to true/false, the response does change that field.

Is there something that is happening under the hood that I'm not aware of? Also what exactly does the "has_downloads" field configure? I could not find anything in my repository settings about it or when searching around for the meaning of it.

**Comment by travi** [comment]
having not interacted with that in the past, my assumption is that it is related to the deprecated [downloads api](https://developer.github.com/v3/repos/downloads/). i notice that the [repository response](https://developer.github.com/v3/repos/#get) also has a `downloads_url` that seems to also be related to that api.

while `settings` does enable configuring repository settings, you'll probably have better luck getting questions like this answered on https://github.community/ or by emailing github support if you can't find them directly in the [api documentation](https://developer.github.com/v3/).

**Comment by kevo1ution** [comment]
Thanks, I'll check out the community
