### ISSUE TITLE
Get config from app.json

### ISSUE THREAD

**Issue by bkeepers** [probot/settings#17]
> app.json is a manifest format for describing web apps. It declares environment variables, add-ons, and other information required to run an app on Heroku. This document describes the schema in detail.
>
> –[Heroku Dev Center](https://devcenter.heroku.com/articles/app-json-schema)

It has `description` and `website`, and the `keywords` could become topics.

**Comment by knrt10** [comment]
@bkeepers would you please explain what exact implementation you want in this?
