### ISSUE TITLE
create issue templates

### ISSUE THREAD

**Issue by travi** [probot/settings#174]
it would be helpful to ask a few questions up front to have a better idea of the context of where the error was experienced

* using the public instance (currently does not produce error output)
* running own instance against public github
* running own instance against github enterprise

**Comment by travi** [comment]
looks like the `config.yml` needs to be added for the prompt with choices to show up

**Comment by gr2m** [comment]
Hmm I don't have a `config.yml` e.g. in https://github.com/gr2m/twitter-together/tree/master/.github/ISSUE_TEMPLATE and it just works

**Comment by travi** [comment]
interesting. thats what i expected as well 🤔 docs aren't super clear about what the important details are. i wonder if it's the `about` detail that i left off
