### ISSUE TITLE
[Bug] `Automatically delete head branches` option changing

### ISSUE THREAD

**Issue by carusogabriel** [probot/settings#185]
Hey all 👋 

I've started to test this repo here at @usabilla and we've noticed a weird behavior (step-by-step):

1. We have the `Automatically delete head branches` option checked in `repository-a`
2. We change the `master` branch protection to allow @dependabot as a trusted app
3. The `Automatically delete head branches` option is now unchecked (???)

How is that possible if GitHub's API does not have anything related to that option yet?

Keep up the good working 👏🏻

**Comment by travi** [comment]
that is an interesting observation. thank you for sharing. this does sound like behavior that could be resolved by [enabling settings to configure that flag](https://github.com/probot/settings/issues/134), but as you mention, it wasn't available in the api the last i knew.

would you be interested in emailing github support to see if they can explain what you're seeing? if it is available through the api now, it would be great to enable configuration, which i suspect would resolve this issue as well.

**Comment by carusogabriel** [comment]
@travi I'll contact them via https://support.github.com/ and I update this issue as soon as I get a reply.

**Comment by kevo1ution** [comment]
@carusogabriel https://github.com/octokit/rest.js/issues/1530 It's an issue with the endpoint itself: `PATCH /repos/:owner/:repo` will always disable the `Automatically delete head branches`. Github support team responded and said they were able to recreate the issue and that the engineering team is working on it.

**Comment by carusogabriel** [comment]
@kevo1ution Perfect, thanks for the update 👍

**Comment by carusogabriel** [comment]
I'm gonna close this issue as this is something related to GitHub itself, not this App. Thanks for the support, either way.

**Comment by localheinz** [comment]
Interestingly, the API, albeit not documented, supports enabling/disabling the setting via the `delete_branch_on_merge` key.

However, it looks like it's not supported via `probot/settings`.
