### ISSUE TITLE
Support for Branch Protection's "Require linear history"

### ISSUE THREAD

**Issue by tomislacker** [probot/settings#220]
## Prerequisites:

> Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.

Yes

![2020-04-07_13-25](https://user-images.githubusercontent.com/1132557/78701527-30c7f780-78d5-11ea-9622-0629b6fcbd4a.png)

> Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).

Yes
* https://developer.github.com/v3/repos/branches/#get-branch-protection
* https://developer.github.com/v3/repos/branches/#update-branch-protection

## New Feature

Have the ability for a new `settings.yml` parameter to toggle the _"Require linear history"_ feature within branch protection.

**Comment by travi** [comment]
are branch protection settings working for you otherwise? there are some quirks about the interaction between this app and the api that still need to be smoothed out, but if you follow the [notes in the readme](https://github.com/probot/settings#notes), it should be possible to get it working. 

since `required_linear_history` is just another property on that api call, i would expect it to work if the protection call succeeds otherwise

**Comment by johnmartel** [comment]
@travi I can confirm that `required_linear_history` and `required_signatures` do work, even though the latter is not documented as being part of [updateBranchProtection](https://developer.github.com/v3/repos/branches/#update-branch-protection) but as [its own request](https://developer.github.com/v3/repos/branches/#add-required-signatures-of-protected-branch) :)

**Comment by travi** [comment]
> I can confirm that `required_linear_history` and `required_signatures` do work

great news. does this mean that this issue should be closed?

**Comment by johnmartel** [comment]
@travi As far as the enhancement request goes, it can be closed as it it already working.

Maybe @tomislacker can confirm, based on my linked example, that he can solve his issue.

**Comment by tomislacker** [comment]
Definitely works! My apologies for not getting a chance to test sooner. Thanks all!

**Comment by travi** [comment]
thanks for confirming @tomislacker and @johnmartel :)

**Comment by dixon-kun** [comment]
Thanks guys
