### ISSUE TITLE
INFO Level Error ERROR event: Resource not accessible by integration

### ISSUE THREAD

**Issue by maheshrajannan** [probot/settings#223]
## Problem Description

1) Change the repo name through settings.yml file.
2) Refresh the screen.
3) The repo name changes correctly as expected.
4) With a few glitches in the logs on the server(OCP-Open Shift) hosting the app.

So basically this error happens when a payload is sent from github dev environment to the node js github settings app running on OCP, the github settings app processes it successfully and returns the response..

Then there seems to be something wrong (Call back stack?) and there is status code 500 error, in the advanced tab under settings github app...

This error will NOT print if you change nodeenv to production. In dev environment when i put nodeenv as dev, i see the below INFO level error.

22:58:44.601Z  INFO probot: Listening on http://localhost:3000 
Push Event Received
{ Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/opt/app-root/src/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at Object.Logger.stdSerializers.err (/opt/app-root/src/node_modules/bunyan/lib/bunyan.js:1148:19)
....
  event: {
    "event": "push",
    "id": "REDACTED",
    "installation": REDACTED,
    "repository": "REDACTED-org/REDACTED-2-abc"
  }
22:59:12.905Z ERROR probot: Resource not accessible by integration
  HttpError: Resource not accessible by integration
      at response.text.then.message (/opt/app-root/src/node_modules/@octokit/request/dist-node/index.js:66:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)

### Error output, if available

```

```

**Comment by maheshrajannan** [comment]
We are an enterprise user. I will ask my team. if i can include some of the redacted info.

**Comment by travi** [comment]
is this still an issue after [the permissions adjustments that you made](https://github.com/probot/settings/issues/224#issuecomment-616621885)?
