### ISSUE TITLE
Labels are not working

### ISSUE THREAD

**Issue by maheshrajannan** [probot/settings#224]
## Problem Description

Changing the label below in ./github/settings.yml has no effect on either existing issues or new issues and there are no new labels created.

# Labels: define labels for Issues and Pull Requests
```
labels:
  - name: bot-bug
    color: CC0000
    description: A bot-bug for testing
```

### What is actually happening

Changing the label below in ./github/settings.yml has no effect on either existing issues or new issues and there are no new labels created.

### What is the expected behavior

It should have some effect to start with.

### Error output, if available

```

```

### Are you using the hosted instance of probot/settings or running your own?
Yes.
### If running your own instance, are you using it with github.com or GitHub Enterprise?
Github Enterprise
#### Version of probot/settings
latest.
#### Version of GitHub Enterprise
GitHub Enterprise Server 2.20.0

**Comment by travi** [comment]
> Yes.

This doesn't clarify between the two options, but since you're using GitHub enterprise that means that you must be running your own instance, correct? 

Logs showing the error output would be really helpful to understand the problem. I am not aware of any issues with these calls in the public instance.

**Comment by maheshrajannan** [comment]
yes. Running our own instance in OCP.
This one started working after correcting permission for repo, with respect to the app.

Thanks
Mahesh

**Comment by ap0phi5** [comment]
>  you're using GitHub enterprise that means that you must be running your own instance, correct?

@travi @maheshrajannan FWIW, There is **GitHub Enterprise Cloud** which are extended features on github.com as well as **GitHub Enterprise Server** which is a self-hosted instance.

**Comment by travi** [comment]
> This one started working after correcting permission for repo, with respect to the app.

great to hear. would you mind closing the issues that are working now if there is no further follow up needed?

**Comment by travi** [comment]
> FWIW, There is GitHub Enterprise Cloud which are extended features on github.com as well as GitHub Enterprise Server which is a self-hosted instance.

right, which makes it a bit difficult to investigate issues from this end without appropriate context of how the instance of probot/settings is running. i may need to give some thought on the questions in the issue template to possibly improve the clarity of the questions and get better context initially.

**Comment by ap0phi5** [comment]
@travi We are GHEC users and are quite versed with the flavours of GH. If you like, I'll do a PR later for your ISSUE_TEMPLATE. For GH/GHEC, it is still the same API. There are a few nuances, E.g. for repository types 'Private/Public', you also have 'Internal'.
The key difference with GHES is that it has a different URL and will be an older spec of the API (with no guarantee of which version as the GHES version is maintained by the end user).

**Comment by travi** [comment]
@ap0phi5 while i'm aware of the variations, the tricky part is to ask the right questions to gain the context needed to understand how probot/settings is running in each case. 

the main things we are looking for are:
* you run your own instance, so you have access to logs but might be behind on version
* you use the hosted version that is always running the latest version, but you don't have access to logs

if you have thoughts about improving the issue template to better pull that information, i would welcome a PR :)

**Comment by travi** [comment]
i'm going to go ahead and close this issue since the original problem appears to be resolved by fixing permissions issues. i'll consider improvements to the issue template, but i think those are separate from this issue. feel free to open an issue or PR related to that or other things that are separate from this issue

**Comment by justinmchase** [comment]
Can you clarify what permissions needed to be fixed?
