### ISSUE TITLE
Cannot manage teams: 404 not found

### ISSUE THREAD

**Issue by jsok** [probot/settings#235]
## Problem Description

Trying to manage teams via `settings.yml` results in an error.

### What is actually happening

Adding a team that isn't already in the teams page, e.g.

```yaml
teams:
  - name: ghe-admins
    permission: admin
```

Delivery of the event fails:

![Screen Shot 2020-05-13 at 4 34 23 pm](https://user-images.githubusercontent.com/737907/81779226-a445d000-9537-11ea-845e-05d983c1d16d.png)

### What is the expected behavior

The team is added to the repository.

### Error output, if available

```
{
  "name": "github",
  "hostname": "ad4f9a1b2614",
  "pid": 59,
  "installation": "21",
  "level": 20,
  "params": {
    "baseUrl": "https://github.example.com/api/v3",
    "mediaType": {
      "format": "",
      "previews": []
    },
    "request": {
      "validate": {
        "org": {
          "required": true,
          "type": "string"
        },
        "owner": {
          "required": true,
          "type": "string"
        },
        "repo": {
          "required": true,
          "type": "string"
        },
        "team_slug": {
          "required": true,
          "type": "string"
        }
      },
      "retryCount": 1
    },
    "team_slug": "ghe-admins",
    "owner": "MyOrg",
    "repo": "example-repo",
    "branch": "master",
    "required_pull_request_reviews": {
      "required_approving_review_count": 1,
      "dismiss_stale_reviews": true,
      "require_code_owner_reviews": true,
      "dismissal_restrictions": {}
    },
    "required_status_checks": {
      "strict": false,
      "contexts": []
    },
    "enforce_admins": false,
    "restrictions": null,
    "org": "MyOrg"
  },
  "msg": "GitHub request: DELETE /orgs/:org/teams/:team_slug/repos/:owner/:repo - 404",
  "time": "2020-05-13T06:16:08.283Z",
  "v": 0
}
```

### Are you using the hosted instance of probot/settings or running your own?

Own instance of probot/settings.

### If running your own instance, are you using it with github.com or GitHub Enterprise?

GitHub Enterprise

#### Version of probot/settings

Even with master as of today, i.e. https://github.com/probot/settings/tree/84a158a20c7ea9d19785bf0c655cbc689370aeea

#### Version of GitHub Enterprise

2.19.3

#### App Permissions

![app-permissions](https://user-images.githubusercontent.com/737907/81779139-706aaa80-9537-11ea-9ee3-15c91c151fda.png)

**Comment by jsok** [comment]
It would seem that the endpoints for deleting teams from a repo are different for:
* github.com: https://developer.github.com/v3/teams/#remove-team-repository
  `DELETE /orgs/:org/teams/:team_slug/repos/:owner/:repo`
* github enterprise: https://developer.github.com/enterprise/2.19/v3/teams/#remove-team-repository
  `DELETE /teams/:team_id/repos/:owner/:repo`

**Comment by gr2m** [comment]
just to confirm, there was a recent change, and more changes of that kind are coming. We can address the differences in https://github.com/octokit/plugin-enterprise-compatibility.js/, which is already included in Probot

**Comment by travi** [comment]
@jsok thanks for reporting and apologies for the disruption. please let me know if you still see any issues after these updates

**Comment by jsok** [comment]
@travi appreciated, have tested on local GHE 2.19 instance and team management functionality is working.
