### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by danielbachhuber** [probot/settings#25]
It would be helpful to have a `CONTRIBUTING.md` so I know how to set up the project locally and make changes (and/or test those changes in a live environment).

**Comment by bkeepers** [comment]
👍 Here are some docs for getting started: https://github.com/probot/probot/blob/master/docs/development.md.

A `CONTRIBUTING.md` should be added to https://github.com/probot/plugin-template and then copied to all the existing plugins.

**Comment by danielbachhuber** [comment]
Lol, I just ran into my old issue 😄
