### ISSUE TITLE
Add support for topics

### ISSUE THREAD

**Issue by nikolay** [probot/settings#26]

**Comment by danielbachhuber** [comment]
👍 I had it on my todo list to create this issue.

(hi @nikolay !)

**Comment by nikolay** [comment]
@danielbachhuber Nice to see you contributing to such a fine project! Maybe I could help, too!

**Comment by nikolay** [comment]
From https://developer.github.com/v3/repos/:

>Note: The `topics` property for repositories on GitHub is currently available for developers to preview. To view the `topics` property in calls that return repository results, you must provide a custom media type in the `Accept` header:
>```
>application/vnd.github.mercy-preview+json
>```
