### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jme7** [probot/settings#284]
If someone is using this in they're repository, then make sure anyone can open a pull request with settings.yaml changed, but only admins will be able to push the PR (If this is possible)

**Comment by travi** [comment]
As mentioned [in the README] (https://github.com/probot/settings#security-implications), the best way to accomplish this at this time is to leverage GitHub's codeowners feature.

**Comment by Jme7** [comment]
Oh, sorry, I didn't see that. Just thought of that and wanted to mention it.

**Comment by travi** [comment]
not a problem. i hope that accomplishes what you are after. thanks for your interest

**Comment by Jme7** [comment]
Yes, it did, and I also now know about CODEOWNERS, which can be useful.
