### ISSUE TITLE
Add support for copying settings from a 'default' repository

### ISSUE THREAD

**Issue by bkeepers** [probot/settings#29]
When managing a project that has a lot of similar repositories, it would be helpful to have one repository with defaults that other repositories inherit from.

How it would work:

1. Create a repository named `default`, which has templates and a config for new repositories
1. When a new repository is created, it will automatically open a pull request that copies over the templates, one of which would be a `.github/config.yml` with an option that tells it to inherit from the default
1. Any future changes to the config in the `default` repository would be synced to repositories that inherit from it

**Comment by danielbachhuber** [comment]
Another implementation could be an `inherit: <url>` attribute, which inherits settings from an arbitrary YAML file.

This way, the inheritance would be just in time, instead of involving syncing.

**Comment by ntwb** [comment]
FYI: `probot-config` now supports this via `_extends`, see https://github.com/getsentry/probot-config#setup

**Comment by knrt10** [comment]
@ntwb Yeah I stumbled upon it 2 days before.

**Comment by travi** [comment]
I still think this would be a big help. The `probot-config` extension mentioned above sounds like a great solution. That's not already supported here, correct?

**Comment by travi** [comment]
Still relevant

**Comment by jwsloan** [comment]
This can be accomplished today. We have a `.github` repo with a `settings.yml` file in it, and we extend that from there.
