### ISSUE TITLE
[question] Affect of protected branches on warning item at bottom of readme

### ISSUE THREAD

**Issue by patcon** [probot/settings#30]
I might have expected the stern warning at the bottom of readme might be caveated by enabling of protected branch features.

If it's true that not features of protected branches (ie waiting for +1 or something) can mitigate the "push" = "admin" warning, it would be helpful to acknowledge that in the warning, so readers know that it's not simply an oversight :)

**Comment by bkeepers** [comment]
> I might have expected the stern warning at the bottom of readme might be caveated by enabling of protected branch features.

This is a great point. Something like https://github.com/probot/dco/blob/master/docs/required-statuses.md would be great to include in the docs.

> …so readers know that it's not simply an oversight :)

I'm pretty sure it's just an oversight, but need to test it to be sure.

**Comment by bkeepers** [comment]
I looked at this a little today. Protected branches would work, but it's not ideal as-is. You could protect `master` and enable "Restrict who can push to this branch". This will require the specified people/teams to merge every pull request.

> …(ie waiting for +1 or something)…

This will be the key. Here's what would probably be required to make this a good experience:

1. When this plugin is installed, it protects `master` and adds a required status (maybe add a config to disable this)
1. When a change is made to `.github/config.yml`, the status is set to failing unless it is authored by of there is an approved review from someone with admin rights

This shouldn't be too difficult to implement if someone wants to tackle it. It probably won't be a priority for me for a while.
