### ISSUE TITLE
when will the branch functionality be available in github.com/app/settings

### ISSUE THREAD

**Issue by sdmattheww** [probot/settings#366]
Hi All,
I'm wondering when I will be able to use the branch functionality in the official app located at github.com/app/settings.  I'd like to avoid running my own instance if possible.  Thanks!

**Comment by travi** [comment]
could you describe what you mean by "branch functionality"? is there an existing open issue related to this feature?

as a single maintainer, finding the time to include new features is tight. giving me clear information is very helpful for me to understand where that time could be best spent.

if you are already running your own instance with modifications that you would like to see here, i'm open to working through a PR to potentially include your change here.

**Comment by sdmattheww** [comment]
Thanks for your response and sorry if this isn't clear.  The master branch README includes this section

`branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true`

But the github app that you can install from github.com/app/settings does not include that section in the README and thus I cannot manage branch protections.

**Comment by travi** [comment]
the documentation at github.com/app/settings is overdue for an update, but the code executing there is the latest version of this application.

branch protection does work, but you need to be careful and configure it correctly. a common mistake is not including some of the required attributes. be sure to check the documentation for the api endpoint to ensure that you are including all of the necessary details.

**Comment by sdmattheww** [comment]
Perfect, I got it sorted out.  Thank you!

**Comment by travi** [comment]
great to hear! thanks for following up
