### ISSUE TITLE
Change location of settings file

### ISSUE THREAD

**Issue by ScottChapman** [probot/settings#403]
I'd like to change the path where the settings app settings.yml file.
I've seen the path here: https://github.com/probot/settings/blob/master/lib/settings.js#L23
I assume I can just change that in my branch (though I suspect that'll break a bunch of the tests), but I wonder is there a more formal place where this is specified?

**Comment by travi** [comment]
changing that value is one piece, but you will also need to update the permissions granted to your instance since the ability to read the file is typically limited to the specific file. restricting the permissions we ask for is a big part of the reason we are not able to offer more flexibility in the hosted instance.

**Comment by ScottChapman** [comment]
yea, I know I'll have to give the app permission to read/write that file too (I am deploying it myself).

**Comment by ScottChapman** [comment]
I tried just making that change, giving the app permission to read/write the file, re-deployed. But it doesn't appear to work...

**Comment by ScottChapman** [comment]
setting env var `LOG_LEVEL=trace` did not give any additional tracing either.

**Comment by travi** [comment]
did you also update this one?

https://github.com/probot/settings/blob/669e7bf8c400e61944c3df2b0525050c6437db05/index.js#L8

**Comment by ScottChapman** [comment]
I did not, as I just changed the containing folder. Left the filename the same.

**Comment by travi** [comment]
ah, moving to a different folder gets a bit more complicated since `context.config` makes some assumptions. see https://github.com/probot/probot/blob/9483546c740ae36d0e3fb68fbdb9f91bf1985ec2/docs/best-practices.md#store-configuration-in-the-repository for more details

**Comment by ScottChapman** [comment]
Oh wow. So, maybe it's not worth trying to do that...

**Comment by travi** [comment]
seems like the open questions here are answered, so i'm going to close. if there is something more that would be helpful, feel free to reopen
