### ISSUE TITLE
Add support for "Automatically delete head branches"

### ISSUE THREAD

**Issue by yotamshapira** [probot/settings#428]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
Yes: https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
I couldn't find an API for this.

* If the functionality is not yet available in the API, it would be helpful if you
  contacted support (https://support.github.com/) or posted in the Community Forum (https://github.community/). Please
  include a link to the forum post if you create one or a copy of the response from support.
https://github.community/t/missing-api-for-automatically-delete-head-branches/176587

## New Feature

Please describe the desired new functionality:
Add a new entry to the `settings.yml` to enable control over the "Automatically delete head branches" option.

Thanks!

**Comment by johnmartel** [comment]
@yotamshapira does the following from the documentation solve your issue?

```yaml
repository:
  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true
```

**Comment by yotamshapira** [comment]
> @yotamshapira does the following from the documentation solves your issue?
> 
> ```yaml
> repository:
>   # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
>   delete_branch_on_merge: true
> ```

It does, thanks!
