### ISSUE TITLE
Support alternate root dir

### ISSUE THREAD

**Issue by ScottChapman** [probot/settings#449]
it looks like `.github` is the anchored root for the config files. I wanted to be able to have these in a different folder structure, but it appears to always prepend `.github` to my path.

**Comment by ScottChapman** [comment]
Yea, I am doing our own self-hosted GHE instance. And I use that plugin for other apps.

It's actually done here: https://github.com/probot/probot/blob/master/src/context.ts#L216 (will move this to probot instead)
It seems reasonable to have that be the default, but it would be useful to have that be a config setting perhaps. hardcoding an alteration to the path just prevents someone from having control over where they manage their files.

**Comment by travi** [comment]
closing in favor of https://github.com/probot/probot/issues/1549
