### ISSUE TITLE
node-ci cache and GitHub Action

### ISSUE THREAD

**Issue by oscard0m** [probot/settings#472]
After adding native `cache` support for `setup-node` action I have some doubts on this step:
https://github.com/probot/settings/blob/b0ca60a3a6f8e498e0c7cf98742707f68c3ada45/.github/workflows/node-ci.yml#L21

Is it adding a cache so it can be replaced by a regular `npm install` or `npm ci` ? Or is there anything else to keep this step (and maybe rollback `cache` feature from `setup-node` step)?

**Comment by gr2m** [comment]
yes we can remove the `uses: bahmutov/npm-install@v1` step now
