### ISSUE TITLE
Branch protection rules and collaborators are not set properly

### ISSUE THREAD

**Issue by alexey-anufriev** [probot/settings#490]
## Problem Description

When I supply both: `collaborators` with some users/teams as well as `branches.protection.restrictions` that are using those users/teams the latter stays empty. It looks like collaborators must be added first before they are available for branch protection rules. And having the configuration that supplies both does not work. I suspect that branch protection rules were added first, and only after there is an attempt to add collaborators. Thus collaborators are added but not referenced from rules.

### What is the expected behavior

Both, collaborators and branch protection rules that reference those are set properly.

### Are you using the hosted instance of probot/settings or running your own?

Running own.

### If running your own instance, are you using it with github.com or GitHub Enterprise?

GitHub Enterprise

**Comment by foolioo** [comment]
That is a well known "issue". The right way to handle it, is to introduce the changes in to iterations. The first iteration is to set the contributors, and only after they contributors got access to the repository, you need to set the branch protection rules that depends on these contributors in the second iteration.

**Comment by alexey-anufriev** [comment]
I agree, but this should still be handled by Probot.

**Comment by foolioo** [comment]
> this should still be handled by Probot

You should consider to contribute a PR with this behavior.

**Comment by travi** [comment]
closed by #591
