### ISSUE TITLE
Add support for configuring milestones

### ISSUE THREAD

**Issue by bkeepers** [probot/settings#5]
See API docs for [creating a milestone](https://developer.github.com/v3/issues/milestones/#create-a-milestone)

**Comment by AshanthaLahiru** [comment]
Hey @bkeepers , I'm currently working on this. When I create a milestone, it calls to getMilestones request call. It's kind of weird but code seems fine to me. I'm testing this by redelivering the payload. Any suggestions?
 
![issue](https://user-images.githubusercontent.com/22785263/37464797-7bc93fb2-287f-11e8-81bf-83330b5f9f82.PNG)

**Comment by bkeepers** [comment]
Can you open a PR with the code you have in progress so I can look more closely?

**Comment by AshanthaLahiru** [comment]
Sure. that would be great.

**Comment by AshanthaLahiru** [comment]
Hey @bkeepers , found the issue. It was a problem with the `@octokit/rest` version. Mine was `@octokit/rest": "14.0.9`, which doesn't clone the options object as below.

![issue-found](https://user-images.githubusercontent.com/22785263/37545124-9b75ecca-298d-11e8-9844-9759d58f075c.PNG)

Thank you for your time :smiley: 

Still wonder why it installs Probot version 5.6.0, even Settings's dependency set it to be 6.0.0!

**Comment by AshanthaLahiru** [comment]
Yes, @bkeepers, I think this `enhancement` is good to go. Let me know if there is anything to be changed. I can make those changes as well. :slightly_smiling_face:
