### ISSUE TITLE
Validate configuration and update the status

### ISSUE THREAD

**Issue by bkeepers** [probot/settings#6]
When `.github/config.yml` is changed in other branches, it should check the config syntax and report any errors or warnings via the status API.

**Comment by knrt10** [comment]
@bkeepers how would you want to check the status? What I am getting is that if  ```settings.yml``` is changed in other branches bot will do a test on it. Am i right? 
What I am not getting is that how the checking will be done?
Please correct me and explain.

Thanks in advance.

**Comment by bkeepers** [comment]
@knrt10 whenever a `push` event is received that modifies `.github/settings.yml`, the app should validate the config file and set a [commit status](https://developer.github.com/v3/repos/statuses/) with the result.

**Comment by knrt10** [comment]
@bkeepers I am successfully getting the contents of the file can you give me any idea how to check the validation of config file?

Thanks in advance.

**Comment by knrt10** [comment]
@bkeepers Please review my PR and suggest changes if any.

Thanks in advance.
