### ISSUE TITLE
Update app name/link on Installation page

### ISSUE THREAD

**Issue by whizark** [probot/settings#62]
The description on installation page still shows old `probot/configurer`. (GtiHub account > Seetings > Applications > Setings > Configure)
Shouldn't be `probot/settings` ? :smiley_cat: 

![probot-settings](https://user-images.githubusercontent.com/1211058/36364297-a9377a1a-1586-11e8-8539-0a19f2174af2.png)

**Comment by bkeepers** [comment]
Thanks @whizark, I've updated it!
