### ISSUE TITLE
Add support for label descriptions and emoji

### ISSUE THREAD

**Issue by ntwb** [probot/settings#63]
https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more
> Emoji -When words are just not enough, include emoji in your labels to express yourself and the needs of your project through tiny images. ✨
>
> Descriptions - Add descriptions to your labels to provide even more context and help your contributors apply the right ones to their issues or pull requests. Descriptions will appear when you hover your mouse over labels around GitHub.

**Comment by ntwb** [comment]
Oh, I missed the warning 8 days ago 😞 

Still relevant, would be great to see the probot settings app support emoji labels

**Comment by pholleran** [comment]
Documenting here that emoji labels work with this app as long as the label name is passed in double quotes

```yaml
  - name: ":hand: help wanted"
    color: 128A0C
```
