### ISSUE TITLE
Add Instructions/Suggestion To Documentation To Use Code Owners as Permission Work Around

### ISSUE THREAD

**Issue by romeara** [probot/settings#64]
I noticed the current documentation points out the security issue of push-access users effectively getting admin via this application. 

One suggestion that might be worth adding to the documentation is setting admins as the code owner of the yaml file, and then selecting the option to require code-owner review for the repository. It allows others to suggest changes via pull-request, but an admin still has to approve it. Not the most dynamic solution (requires update separate from the permissions), but it's something.

If the team things this is worth doing, I'd be happy to put together a pull request (either to add to the main readme or add a separate markdown file like deploy.md to link to from the main one)

**Comment by bkeepers** [comment]
👍 pull requests welcome.

**Comment by romeara** [comment]
Pull request made (#66 )

**Comment by bkeepers** [comment]
Thanks!

**Comment by romeara** [comment]
My pleasure!
