### ISSUE TITLE
[support] app doesn't seem to be responding to settings.yml changes

### ISSUE THREAD

**Issue by patcon** [probot/settings#83]
I had the `settings` app enabled on my one repo (and then globally, just to be sure), and pushing updates didn't seem to have any effect. Am I doing this right?

https://github.com/patcon/sample-civictech-app

![screenshot](https://i.imgur.com/Dzvjrc1.png)

**Comment by patcon** [comment]
Yep, I did -- both via PR and directly. Real odd.

Can anyone reproduce?

- [ ] fork repo to personal account
- [ ] enable settings plugin on repo
- [ ] add a newline in settings.yml via GitHub UI

**Comment by patcon** [comment]
Just tried the above again (minus the fork), and no dice.

**Comment by knrt10** [comment]
let me debug and get back to you.

**Comment by knrt10** [comment]
I found it. Problem you are facing is beacuse of description. Try removing :balloon: . Try it @patcon .

**Comment by knrt10** [comment]
Its because after `description : ` the yaml file is reading `:ballon:` as another key and hence not following format of yaml file.
